# -*- coding: utf-8 -*-
"""a_pp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YSE4ADaA9_WjtShhhIDkDB6i-oWSX6WO
"""

!pip install streamlit

import streamlit as st
import requests
from datetime import datetime

# Page setup
st.set_page_config(page_title="Rain Check ☔", layout="centered")

st.markdown("## ☁️🌦️ **Current Rain Forecast via Voice Input** ⛅🌧️")

# Use audio input widget
audio_input = st.audio_input("🎙️ Speak or type your city name:")

city = None

# If user types, take text; else, if audio provided, attempt to transcribe
if "http" in str(audio_input):
    st.write("✅ Audio captured. Sending for transcription...")

# For simplicity, simulate speech-to-text using openAI Whisper endpoint if available
if audio_input:
    # Optionally send to a STT service here and get `city = transcribed_text`
    st.write("ℹ️ Transcription not implemented—please type manually instead.")
    st.text_input("Or type your city:", "")

else:
    city = st.text_input("🌍 Or just type your city:", "Chennai")

if city and st.button("🔍 Check Weather Now"):
    # (your existing weather code here)
    url = f"https://api.openweathermap.org/data/2.5/weather?q={city}&appid=YOUR_API_KEY&units=metric"
    # ...