# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TZVzIAsV6toQsyPN1stYRPvE_YKlt2jx
"""

!pip install streamlit

import streamlit as st

# Custom CSS for background and styles
st.markdown("""
    <style>
        body {
            background-image: url('https://images.unsplash.com/photo-1501594907352-04cda38ebc29?auto=format&fit=crop&w=1920&q=80');
            background-size: cover;
            background-repeat: no-repeat;
            background-attachment: fixed;
        }
        .main {
            background-color: rgba(255, 255, 255, 0.85);
            padding: 2rem;
            border-radius: 10px;
        }
        h1, h2, h3, h4 {
            color: #002244;
            text-align: center;
        }
        .emoji {
            font-size: 26px;
        }
    </style>
""", unsafe_allow_html=True)