# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1trbuaUr7mmFk-GAMQBkOy2brj0LGDHnH
"""

!pip install streamlit

import streamlit as st
import requests
from datetime import datetime

# Set page configuration
st.set_page_config(page_title="Rain Check ☔", layout="centered")

# Custom CSS for background and styles
st.markdown("""
    <style>
        body {
            background-image: url('https://in.images.search.yahoo.com/images/view;_ylt=Awrx.HjnKVRoOogb25O9HAx.;_ylu=c2VjA3NyBHNsawNpbWcEb2lkAzdmOWI2Yjc4NTg3M2RhMTRlYjEwNjEwMjc2NWU3MmQzBGdwb3MDMTUEaXQDYmluZw--?back=https%3A%2F%2Fin.images.search.yahoo.com%2Fsearch%2Fimages%3Fp%3Draining%2Bimages%2Bhd%26type%3DE210IN826G0%26fr%3Dmcafee%26fr2%3Dpiv-web%26tab%3Dorganic%26ri%3D15&w=1920&h=1080&imgurl=getwallpapers.com%2Fwallpaper%2Ffull%2F5%2Ff%2Fe%2F1212949-raining-hd-wallpapers-1920x1080-image.jpg&rurl=https%3A%2F%2Fgetwallpapers.com%2Fcollection%2Fraining-hd-wallpapers&size=404KB&p=raining+images+hd&oid=7f9b6b785873da14eb106102765e72d3&fr2=piv-web&fr=mcafee&tt=Raining+HD+Wallpapers+%2872%2B+images%29&b=0&ni=21&no=15&ts=&tab=organic&sigr=kh2afzWKhcio&sigb=uO_zfHdF96.t&sigi=nuVQkOBn0WTg&sigt=1xZkN.elf_nz&.crumb=IzszreHrvsn&fr=mcafee&fr2=piv-web&type=E210IN826G0');
            background-size: cover;
            background-repeat: no-repeat;
            background-attachment: fixed;
        }
        .main {
            background-color: rgba(255, 255, 255, 0.85);
            padding: 2rem;
            border-radius: 10px;
        }
        h1, h2, h3, h4 {
            color: #002244;
            text-align: center;
        }
        .emoji {
            font-size: 26px;
        }
    </style>
""", unsafe_allow_html=True)

# Create a centered container
with st.container():
    st.markdown("<div class='main'>", unsafe_allow_html=True)

    # Title
    st.markdown("## ☁️🌦️ **Current Rain Forecast** ⛅🌧️")

    # User input
    API_KEY = "0a4819b28a82fa77e5437c6c156837d4"
    city = st.text_input("🌍 Enter your city:", "Chennai")

    if st.button("🔍 Check Weather Now"):
        url = f"https://api.openweathermap.org/data/2.5/weather?q={city}&appid={API_KEY}&units=metric"
        response = requests.get(url)

        if response.status_code == 200:
            data = response.json()

            # Extract current weather data
            temp = data["main"]["temp"]
            humidity = data["main"]["humidity"]
            wind = data["wind"]["speed"]
            weather = data["weather"][0]["description"]
            dt = datetime.fromtimestamp(data["dt"]).strftime("%A, %d %b %Y %I:%M %p")

            # Rain prediction
            rain_expected = "🌧️ **Rain Expected**" if "rain" in weather.lower() else "🌤️ **No Rain**"

            # Output
            st.markdown(f"### 📍 **{city.title()}** — *{dt}*")
            st.markdown(f"#### 🌡️ Temperature: **{temp}°C**")
            st.markdown(f"#### 💧 Humidity: **{humidity}%**")
            st.markdown(f"#### 🌬️ Wind Speed: **{wind} m/s**")
            st.markdown(f"#### 🌀 Condition: **{weather.title()}**")
            st.markdown(f"### ⏱️ Prediction Now: {rain_expected}")

        else:
            st.error("❌ Could not find the city. Please check the spelling.")

    st.markdown("</div>", unsafe_allow_html=True)