# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1trbuaUr7mmFk-GAMQBkOy2brj0LGDHnH
"""

import streamlit as st
import pandas as pd
import numpy as np
import requests
from datetime import datetime
import matplotlib.pyplot as plt

# Title
st.title("Live Weather Forecast and Rain Prediction")

# Get API key and city input
API_KEY = "0a4819b28a82fa77e5437c6c156837d4"
city = st.text_input("Enter your city:", "Chennai")

# Fetch weather data
if st.button("Get Weather Forecast"):
    url = f"https://api.openweathermap.org/data/2.5/forecast?q={city}&appid={API_KEY}&units=metric"
    response = requests.get(url)

    if response.status_code == 200:
        data = response.json()
        forecast_data = []

        for item in data["list"]:
            forecast = {
                "datetime": datetime.fromtimestamp(item["dt"]),
                "temperature": item["main"]["temp"],
                "humidity": item["main"]["humidity"],
                "wind_speed": item["wind"]["speed"],
                "weather": item["weather"][0]["description"]
            }
            forecast_data.append(forecast)

        df = pd.DataFrame(forecast_data)
        st.write("### Weather Forecast Data")
        st.dataframe(df)

        # Visualization
        st.write("### Temperature Trend")
        plt.figure(figsize=(10, 4))
        plt.plot(df["datetime"], df["temperature"], marker='o', color='blue')
        plt.xticks(rotation=45)
        plt.xlabel("Date Time")
        plt.ylabel("Temperature (°C)")
        plt.tight_layout()
        st.pyplot(plt)

        st.write("### Humidity Trend")
        plt.figure(figsize=(10, 4))
        plt.plot(df["datetime"], df["humidity"], marker='s', color='green')
        plt.xticks(rotation=45)
        plt.xlabel("Date Time")
        plt.ylabel("Humidity (%)")
        plt.tight_layout()
        st.pyplot(plt)

        st.write("### Wind Speed Trend")
        plt.figure(figsize=(10, 4))
        plt.plot(df["datetime"], df["wind_speed"], marker='^', color='red')
        plt.xticks(rotation=45)
        plt.xlabel("Date Time")
        plt.ylabel("Wind Speed (m/s)")
        plt.tight_layout()
        st.pyplot(plt)

        # Simple rain prediction based on weather description
        df['Rain_Predicted'] = df['weather'].str.contains("rain", case=False)
        st.write("### Rain Prediction")
        st.dataframe(df[['datetime', 'weather', 'Rain_Predicted']])
    else:
        st.error("Failed to fetch weather data. Please check your city name or API key.")
